"""add team_name and formation to squads

Revision ID: 4fa28a6e0d12
Revises: 058f29c11f31
Create Date: 2026-02-23 20:31:04.003622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa28a6e0d12'
down_revision: Union[str, Sequence[str], None] = '058f29c11f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squads', sa.Column('team_name', sa.String(length=100), nullable=True))
    op.add_column('squads', sa.Column('formation', sa.String(length=20), server_default='4-4-2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squads', 'formation')
    op.drop_column('squads', 'team_name')
    # ### end Alembic commands ###
