"""add_squad_wildcard_ai_decision

Revision ID: d906d91fd1c4
Revises: d602857e663e
Create Date: 2026-02-22 04:23:09.575141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd906d91fd1c4'
down_revision: Union[str, Sequence[str], None] = 'd602857e663e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('squad_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('recommended_player_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_captain_id', sa.String(), nullable=True),
    sa.Column('actual_player_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tot_branch', sa.String(), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('squads', sa.Column('free_transfers_remaining', sa.Integer(), nullable=False))
    op.add_column('squads', sa.Column('wildcard_used', sa.Boolean(), nullable=False))
    op.add_column('squads', sa.Column('wildcard_active_round_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'squads', 'rounds', ['wildcard_active_round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.drop_column('squads', 'wildcard_active_round_id')
    op.drop_column('squads', 'wildcard_used')
    op.drop_column('squads', 'free_transfers_remaining')
    op.drop_table('ai_decisions')
    # ### end Alembic commands ###
